
CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -Wpedantic -ggdb3
LDLIBS=

#-------------------------------------------------------------------------------

.PHONY: all clean

all: song2pmx

clean:
	rm -f song2pmx

song2pmx: src/song2pmx.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

#-------------------------------------------------------------------------------

.PHONY: clean-tex
clean-tex:
	rm -f *.tex *.pdf
	rm -f pmxaerr.dat *.pml  # Generated by `pmxab'
	rm -f *.mx*              # Generated by `pdftex' and `musixflx'

# Three passes are needed for producing the PDF: first with TeX, then with
# `musixflx', and again with TeX. See Section 1.3 "The three pass system" in the
# MusiXTeX manual.
%.pdf: %.tex
	pdftex $<
	musixflx $<
	pdftex $<

%.tex: %.pmx
	pmxab $<
