
CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -Wpedantic -ggdb3
LDLIBS=

#-------------------------------------------------------------------------------

.PHONY: all clean

all: godsong godsong2pmx godsong2lilypond

clean:
	rm -f godsong godsong2pmx godsong2lilypond

godsong: src/generators/godsong.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

godsong2pmx: src/converters/godsong2pmx.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

godsong2lilypond: src/converters/godsong2lilypond.c
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

#-------------------------------------------------------------------------------

.PHONY: clean-tex
clean-tex:
	rm -f *.tex *.pdf
	rm -f pmxaerr.dat *.pml  # Generated by `pmxab'
	rm -f *.mx*              # Generated by `pdftex' and `musixflx'

# Three passes are needed for producing the PDF: first with TeX, then with
# `musixflx', and again with TeX. See Section 1.3 "The three pass system" in the
# MusiXTeX manual.
%.pdf: %.tex
	pdftex $<
	musixflx $<
	pdftex $<

%.tex: %.pmx
	pmxab $<
